# Generated by Django 3.2.5 on 2021-08-11 19:02

import crew.instructor.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[crew.instructor.validators.validate_name])),
                ('surname', models.CharField(max_length=30, validators=[crew.instructor.validators.validate_name])),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField()),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[crew.instructor.validators.validate_mobile])),
                ('email_address', models.CharField(max_length=60, unique=True)),
                ('weight', models.FloatField(blank=True, null=True, validators=[crew.instructor.validators.validate_weight])),
                ('available_from', models.DateField(blank=True, null=True, validators=[crew.instructor.validators.validate_available_from])),
                ('available_to', models.DateField(blank=True, null=True, validators=[crew.instructor.validators.validate_available_to])),
                ('iko_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('iko_level', models.CharField(blank=True, choices=[(None, 'Brak'), ('Asystent', 'Asystent'), ('Instruktor 1', 'Instruktor 1'), ('Instruktor 2', 'Instruktor 2'), ('Insturktor 3', 'Instruktor 3'), ('Coach', 'Coach')], max_length=30, null=True)),
                ('driving_licence', models.BooleanField(default=False, null=True)),
                ('pay_rate_single', models.IntegerField(blank=True, null=True)),
                ('pay_rate_group', models.IntegerField(blank=True, null=True)),
                ('english_lessons', models.BooleanField(blank=True, default=False, null=True)),
                ('kids_lessons', models.BooleanField(blank=True, default=False, null=True)),
                ('group_lessons', models.BooleanField(blank=True, default=False, null=True)),
                ('daily_hour_limit', models.IntegerField(blank=True, null=True)),
                ('tc_accepted_date', models.DateField(blank=True, null=True)),
                ('tc_accepted_flag', models.BooleanField(default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
