# Generated by Django 3.1.2 on 2020-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='driving_licence',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='tc_accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='tc_accepted_flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
