# Generated by Django 3.1.2 on 2020-12-09 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_auto_20201209_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
