# Generated by Django 3.1.2 on 2020-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructor_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='daily_hour_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='iko_level',
            field=models.CharField(blank=True, choices=[('Brak', None), ('Asystent', 'Assistant'), ('Instruktor 1', 'Instructor_1'), ('Instruktor 2', 'Instructor_2'), ('Instruktor 3', 'Insturctor_3'), ('Coach', 'Coach')], max_length=30, null=True),
        ),
    ]
