# Generated by Django 3.1.2 on 2020-12-09 16:00

from django.db import migrations, models
import instructor.instructor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20201209_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='available_from',
            field=models.DateField(blank=True, null=True, validators=[instructor.instructor.validators.validate_available_from]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='available_to',
            field=models.DateField(blank=True, null=True, validators=[instructor.instructor.validators.validate_available_to]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[instructor.instructor.validators.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=30, validators=[instructor.instructor.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='surname',
            field=models.CharField(max_length=30, validators=[instructor.instructor.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[instructor.instructor.validators.validate_weight]),
        ),
    ]
