# Generated by Django 3.1.2 on 2020-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_auto_20201209_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='iko_level',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('Assistant', 'Asystent'), ('Instructor_1', 'Instruktor 1'), ('Instructor_2', 'Instruktor 2'), ('Insturctor_3', 'Instruktor 3'), ('Coach', 'Coach')], max_length=30, null=True),
        ),
    ]
