# Generated by Django 3.1.2 on 2020-12-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_auto_20201209_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='english_lessons',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='group_lessons',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='iko_level',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('Asystent', 'Asystent'), ('Instruktor 1', 'Instruktor 1'), ('Instruktor 2', 'Instruktor 2'), ('Insturktor 3', 'Instruktor 3'), ('Coach', 'Coach')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='kids_lessons',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
