# Generated by Django 3.1.2 on 2020-12-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0007_auto_20201209_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0)),
                ('deadline_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed_flag', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('instructor', models.ManyToManyField(related_name='task', related_query_name='task', to='instructor.Instructor')),
            ],
        ),
    ]
