# Generated by Django 3.2.5 on 2021-08-11 19:02

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[student.validators.validate_name])),
                ('surname', models.CharField(max_length=30, validators=[student.validators.validate_name])),
                ('birth_date', models.DateField(null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True, validators=[student.validators.validate_mobile])),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True, validators=[student.validators.validate_weight])),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('stay_location', models.CharField(blank=True, max_length=40, null=True)),
                ('own_car', models.BooleanField(blank=True, default=False, null=True)),
                ('kite_elsewhere', models.BooleanField(blank=True, default=False, null=True)),
                ('wetsuit_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('S-128', 'S-128'), ('M-140', 'M-140'), ('L-146', 'L-146'), ('XL-152', 'XL-152')], max_length=6, null=True)),
                ('harness_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True)),
                ('iko_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('iko_level', models.CharField(blank=True, choices=[('Level 1 - Discovery', (('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('1E', '1E'))), ('Level 2 - Intermediate', (('2F', '2F'), ('2G', '2G'), ('2H', '2H'), ('2I', '2I'))), ('Level 3 - Independent', (('3J', '3J'), ('3K', '3K'), ('3L', '3L'), ('3M', '3M'), ('3N', '3N'))), ('Level 4 - Advanced', (('4O', '4O'), ('4P', '4P'), ('4Q', '4Q'), ('4R', '4R'), ('4S', '4S'), ('4T', '4T'), ('4U', '4U'), ('4V', '4V'), ('4W', '4W'), ('4X', '4X'), ('4Y', '4Y')))], max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_rate_single', models.IntegerField()),
                ('pay_rate_group', models.IntegerField()),
                ('lesson_hours_sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
