# Generated by Django 3.2.5 on 2021-08-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('group_lesson', models.BooleanField(blank=True, null=True)),
                ('duration', models.FloatField()),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('equipment', models.CharField(blank=True, max_length=30, null=True)),
                ('kite_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('kite_size', models.FloatField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('in_progress', models.BooleanField(blank=True, default=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('instructor', models.ManyToManyField(related_name='lessons', to='instructor.Instructor')),
                ('student', models.ManyToManyField(related_name='lessons', to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('pay_rate', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('iko_level_achieved', models.CharField(blank=True, max_length=10, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
