# Generated by Django 3.1.2 on 2020-12-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
