# Generated by Django 3.1.2 on 2020-10-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField()),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('iko_id', models.IntegerField(blank=True, null=True)),
                ('iko_level', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_rate_single', models.IntegerField(blank=True, null=True)),
                ('pay_rate_group', models.IntegerField(blank=True, null=True)),
                ('english_lessons', models.BooleanField(blank=True, null=True)),
                ('kids_lessons', models.BooleanField(blank=True, null=True)),
                ('group_lessons', models.BooleanField(blank=True, null=True)),
                ('daily_hour_limit', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
