# Generated by Django 3.1.2 on 2020-12-10 02:41

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[student.validators.validate_name])),
                ('surname', models.CharField(max_length=30, validators=[student.validators.validate_name])),
                ('birth_date', models.DateField(null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True, validators=[student.validators.validate_mobile])),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True, validators=[student.validators.validate_weight])),
                ('arrival_date', models.DateField(blank=True, null=True, validators=[student.validators.validate_arrival_date])),
                ('leave_date', models.DateField(blank=True, null=True, validators=[student.validators.validate_leave_date])),
                ('stay_location', models.CharField(blank=True, max_length=40, null=True)),
                ('own_car', models.BooleanField(blank=True, default=False, null=True)),
                ('kite_elsewhere', models.BooleanField(blank=True, default=False, null=True)),
                ('wetsuit_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('S-128', 'S-128'), ('M-140', 'M-140'), ('L-146', 'L-146'), ('XL-152', 'XL-152')], max_length=6, null=True)),
                ('harness_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True)),
                ('iko_id', models.IntegerField(blank=True, null=True)),
                ('iko_level', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
