# Generated by Django 3.1.2 on 2020-10-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('wetsuit_size', models.CharField(blank=True, max_length=3, null=True)),
                ('harness_size', models.CharField(blank=True, max_length=3, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('stay_location', models.CharField(blank=True, max_length=40, null=True)),
                ('iko_id', models.IntegerField(blank=True, null=True)),
                ('iko_level', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
