# Generated by Django 3.1.2 on 2020-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201119_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kite_elsewhere',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='own_car',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
