# Generated by Django 3.1.2 on 2020-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201206_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kite_elsewhere',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='own_car',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
