# Generated by Django 3.1.2 on 2020-12-08 21:57

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201208_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, validators=[student.validators.validate_arrival_date]),
        ),
        migrations.AlterField(
            model_name='student',
            name='leave_date',
            field=models.DateField(blank=True, null=True, validators=[student.validators.validate_leave_date]),
        ),
    ]
