# Generated by Django 3.1.2 on 2020-12-09 14:53

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20201208_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, validators=[student.validators.validate_weight]),
        ),
    ]
